services:
  mongodb:
    build: ./mongodb
    image: testdockerhub28/mongodb:v1
    container_name: mongodb
    volumes: 
    - mongodb:/data/db
  catalogue:
    build: 
      context: ./catalogue
      dockerfile: Dockerfile
    image: testdockerhub28/catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes: 
    - redis:/data
  mysql:
    build: ./mysql
    image: testdockerhub28/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq  
    environment:
       RABBITMQ_DEFAULT_USER: roboshop
       RABBITMQ_DEFAULT_PASS: roboshop123
     
  user:
    build: ./user
    image: testdockerhub28/user:v1
    container_name: user
    depends_on: 
    - mongodb
    - redis
  cart:
    build: ./cart
    image: testdockerhub28/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: testdockerhub28/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  
  payment:
    build: ./payment
    image: testdockerhub28/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    build: ./frontend
    image: testdockerhub28/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - payment
    - shipping
networks:
  default: 
    driver: bridge
    name: roboshop
    external: false #true if you have already created a network manually
volumes:
  mongodb:  #docker volume create mongodb
  redis:
  mysql:
  rabbitmq: